server.port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(H+9W2q/VbXtZnJyXqpEIUT4X3KSYaYkdhJMFK2+YTuG+VChp2A5r69gnJK2akqSSvq2iYJwciP2E67Gj3C4mmEAxrgAZ28qLFwo0KV2yE3JlSrr4cQtvpQ==)
    username: ENC(OExl57i6lGOMQus7EjZsCQ==)
    password: ENC(OJZCIiTajXTZsXDUmpmNbQ==)
  # data.sql
  sql:
    init:
      mode: never  # 데이터베이스 초기화 시 always, 이후 never
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(T0M7FwnJ9dijfGK00reAhBfSh6PQOCU0kjQhmbQmLaA=)
    password: ENC(VLPi588Hc5QuWe+DiihXwVLcgHJ547zTuvsggxhz8JhjNA/CLwJL1A==)
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
  redis:
    host: localhost
    port: 6379

security:
  jwt:
    secret-key: ENC(7q9+u9tv0eO6zvs2VD4f7Ne5lEvmkcQoJ4fx1KH2DU3mxE8rdD4szVECJsXogjuWW6hCJzO0yKmE1d29G7P/PJ+NhIkWwvQ/sQoTWIqdBB7WTqdTdiVUxfSn2orUHhtpKdT5G2sMX4nXs1/tc+6LpyGffJWBMOwKcKmx/7JAj/eSFodOG2B8h1gGEhtylIZvTTO3do1Cv3c=)
    #access-token-expire: 300000
    access-token-expire: 86400000
    refresh-token-expire: 86400000